### ISSUE TITLE
Generated Executable gets detected as Virus

### ISSUE THREAD

**Issue by kwave** [lukaszlenart/launch4j-maven-plugin#41]
A generated exe with UI header gets detected as virus by https://www.avira.com/de/index
This does not happen when using the original launch4j generator with the same config.

**Comment by lukaszlenart** [comment]
Can you use `<infile/>` configuration option? https://github.com/lukaszlenart/launch4j-maven-plugin#version-notes-179

**Comment by kwave** [comment]
Thanks, it worked for a sample executable. But how is this setting related to the virus pattern? Does it do anything different than the direct configuration within the pom does?

**Comment by lukaszlenart** [comment]
Maybe it's because of Launch4j itself - when used with plugin's configuration it's basically work in Ant mode while with `<infile/>` the configuration is passed directly to Launch4j.  I have found few related issues on the internet as well:
https://sourceforge.net/p/launch4j/discussion/332684/thread/d650dfb8/
https://sourceforge.net/p/launch4j/bugs/137/
http://stackoverflow.com/questions/36809182/launch4j-makes-an-antivirus-think-my-java-file-is-a-virus

**Comment by gbiz123** [comment]
Has anyone figured this out? Launch4j is a great tool but it's pretty unfortunate that .exe's generated with it get flagged as malware.

**Comment by lukaszlenart** [comment]
I would suggest using this approach
https://stackoverflow.com/questions/252226/signing-a-windows-exe-file
