### ISSUE TITLE
Overwrite external config options in pom.xml

### ISSUE THREAD

**Issue by tofi86** [lukaszlenart/launch4j-maven-plugin#48]
It would be great to have the following available in your plugin:

```xml
<configuration>
	<infile>${project.basedir}/src/build/launch4j-config.xml</infile>
	
	<versionInfo>
		<fileVersion>${my.version.number}.${my.build.number}</fileVersion>
		<txtFileVersion>${my.version.number}</txtFileVersion>
		<productVersion>${my.version.number}.${my.build.number}</productVersion>
		<txtProductVersion>${my.version.number}</txtProductVersion>
	</versionInfo>
</configuration>
```

so to be able to use an external config file but override several configuration options like version numbers, which are naturally handled within maven.

With the launch4j ant task, this is possible like this:

```xml
<launch4j
	jar="${out.dir}/my.jar"
	outfile="${out.dir}/my.exe"
	configFile="${build.dir}/launch4j/launch4j-config.xml"
	fileVersion="${program.version.number}"
	txtFileVersion="${program.version.txtNumber}"
	productVersion="${program.version.number}"
	txtProductVersion="${program.version.txtNumber}"
/>
```

Any chance to include this in a future version?

Thanks,
Tobias

**Comment by tofi86** [comment]
Also pinging @adamdec as he implemented the original `<infile>` support in PR #32.
Any ideas?

**Comment by adamdec** [comment]
Can you please prepare PR?

**Comment by tofi86** [comment]
Okay, I can give it a try. Seems easier than I thought—also the ANT task solves this a bit _hacky_: https://sourceforge.net/p/launch4j/git/ci/master/tree/src/net/sf/launch4j/ant/Launch4jTask.java#l83

**Comment by myron0815** [comment]
Hej... does this work as expected (in maven)?
Having above configuration... but according to source, i can ONLY override jar/outfile/ and SOME named versioninfo, but not other values?! Why not all?!

Why not just load file in infile.exists(), skip the else and overwrite all with POM values?
(Or the other way round, new config = pom values, and only override from xml)

Got some NPE, b/c i didn't have the specified in xml (since i moved it to pom)

**Comment by lukaszlenart** [comment]
@myron0815 see discussion under #49
